name: MineShop
version: 1.2.0
main: io.github.Taigajid.MineShop.MineShop
api-version: 1.21.4
commands:
  shop:
    description: Der beste Shop der Welt
    usage: /shop
    permission: MineShop.shop.use
    permission-message: Du bist ein Hurensohn!
permissions:
  MineShop.shop.use:
    description: Permission for shop-command
    default: true
